pipeline{
    
    agent{
      docker{
        image 'python:2.7.16-slim'
        args '--user root'
      }
    }

    stages{
        stage('build'){
            when{
                changeset "**/vote/**"
            }
            steps{
                echo 'Compiling vote app'
                dir('vote'){
                    sh 'pip install -r requirements.txt'
                }
            }
        }
        stage('test'){
            when{
                changeset "**/vote/**"
            }
            steps{
                echo 'Running unit Tests on vote app'
                dir('vote'){
                    sh 'nosetests -v'
                }
            }
        }
        
    }

    post{
        always{
            echo 'Pipeline for vote is complete...'
        }
        failure{
            slackSend (channel: "instavote-ci", message: "Build Failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
        success{
            echo 'Pipeline for vote is complete...'
            slackSend (channel: "instavote-ci", message: "Build Succeeded - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
    }
}