pipeline{
    
    agent{
      docker{
        image 'maven:3.8.6'
        args '-v $HOME/.m2/root/.m2'
      }
    }

    stages{
        stage('build'){
            steps{
                echo 'Compiling worker app'
                dir('worker'){
                    sh 'mvn compile'
                }
            }
        }
        stage('test'){
            steps{
                echo 'Running unit Tests on worker app'
                dir('worker'){
                    sh 'mvn clean test'
                }
            }
        }
        stage('package'){
            steps{
                echo 'Packaging worker app'
                dir('worker'){
                    sh 'mvn package -DskipTests'
                }
            }
        }
    }

    post{
        always{
            archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
            echo 'Pipeline for worker is complete...'
        }
    }
}